language: scala

dist: xenial

jdk: openjdk8

scala:
   - 2.12.8

# before_install:
#     - cd $(mktemp -d) && wget --quiet https://git.io/sbt && sudo mv ./sbt /usr/local/bin/sbtx && cd -
#     - sudo chmod 0755 /usr/local/bin/sbtx
#     - make publishlocal

script:
    - make docker_build
    - make docker_test
    - make coverage

after_success:
  - export CODECOV_TOKEN="9837f692-ffac-46db-bc8e-01ef3b9b5b3c"
  - bash <(curl -s https://codecov.io/bash)

# vim: set filetype=yaml fileformat=unix nowrap:
